### ISSUE TITLE
If main fails it is not rejected properly.

### ISSUE THREAD

**Issue by tchar** [GarreauArthur/manage-digital-ocean-managed-database-trusted-sources-gh-action#1]
Hello,

I had an issue with this hook. For some reason fetching the IP address was rejected, `main` did not handle it properly and the next step of my GitHub Action proceeded to run.

Here is an example: 
![image](https://user-images.githubusercontent.com/6424426/213354383-0ad47a94-d20b-4a21-8c8e-c133381e49a1.png)

I will try to create a PR for this.

Cheers,
tchar

**Comment by GarreauArthur** [comment]
Thank you for your participation :smile: 
I modified your PR (#2) a bit, and published a new version of the action.
